"""add token tracking

Revision ID: 0db635d7ea78
Revises: 3f315960e94e
Create Date: 2026-07-17 00:42:28.780599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db635d7ea78'
down_revision: Union[str, Sequence[str], None] = '3f315960e94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('output_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'output_tokens')
    op.drop_column('tickets', 'input_tokens')
    # ### end Alembic commands ###
