"""add extracted email and phone to tickets

Revision ID: 56428a83aa8a
Revises: 7d1271e0f05e
Create Date: 2026-07-17 09:22:26.445865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56428a83aa8a'
down_revision: Union[str, Sequence[str], None] = '7d1271e0f05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ai_extracted_email', sa.String(length=255), nullable=True))
    op.add_column('tickets', sa.Column('ai_extracted_phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'ai_extracted_phone')
    op.drop_column('tickets', 'ai_extracted_email')
    # ### end Alembic commands ###
