"""add compliance and ai extraction columns

Revision ID: 7d1271e0f05e
Revises: ea184797ef62
Create Date: 2026-07-17 07:03:08.651041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1271e0f05e'
down_revision: Union[str, Sequence[str], None] = 'ea184797ef62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('retention_days', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('flagged_for_safety', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'flagged_for_safety')
    op.drop_column('tenants', 'retention_days')
    # ### end Alembic commands ###
