"""add tenant login credentials

Revision ID: 8d08955dbadf
Revises: 56428a83aa8a
Create Date: 2026-07-17 09:55:06.365233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d08955dbadf'
down_revision: Union[str, Sequence[str], None] = '56428a83aa8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('login_email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'tenants', ['login_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_column('tenants', 'hashed_password')
    op.drop_column('tenants', 'login_email')
    # ### end Alembic commands ###
