"""add sender_email, approved_at, citizen_notified_at to tickets

Revision ID: bba58c4b81b5
Revises: 8d08955dbadf
Create Date: 2026-07-17 17:20:32.582913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba58c4b81b5'
down_revision: Union[str, Sequence[str], None] = '8d08955dbadf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('sender_email', sa.String(length=255), nullable=True))
    op.add_column('tickets', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('citizen_notified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'citizen_notified_at')
    op.drop_column('tickets', 'approved_at')
    op.drop_column('tickets', 'sender_email')
    # ### end Alembic commands ###
